id: 093e7092e01bed192b564b04528826cc6f1dbf91
repo: /Users/ajksunkang/workspace/kernelcompass/kernel-src/linux
base_commit: 5f21585384a4a69b8bfdd2cae7e3648ae805f57d
parent_commit: e5f71a27fa12c1a1b02ad478a568e76260f1815e
oracle_files: ["drivers/media/platform/vivid/vivid-vid-cap.c"]
oracle_methods: ["['vivid_update_format_cap', 'drivers/media/platform/vivid/vivid-vid-cap.c']"]
